apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutate-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        securityContext:
          runAsUser: 0  # Violates require-run-as-nonroot.yaml
          allowPrivilegeEscalation: true  # Violates disallow-privilege-escalation.yaml
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"]  # Violates disallow-capabilities-strict.yaml
          seccompProfile:
            type: Unconfined  # Violates restrict-seccomp-strict.yaml
        volumeMounts:
        - name: host-volume
          mountPath: /host
      volumes:
      - name: host-volume
        hostPath:
          path: /etc  # Violates restrict-volume-types.yaml 
